import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./shared/NavBar/NavBar";
import ThemeProvider from "./provider/ThemeProvider";


const poppins = Poppins({
  
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` ${poppins.className} h-full antialiased`}
    >
 
      <body className="min-h-full flex flex-col bg-white dark:bg-[#06111F]">
       <ThemeProvider>
    <NavBar />
    {children}
  </ThemeProvider>
        </body>
    </html>
  );
}
